# Getting Youtube transcripts programmatically https://github.com/jdepoix/youtube-transcript-api

#install
pip install youtube_transcript_api

# video id: akB4kfdBzBU
transcript = YouTubeTranscriptApi.get_transcripts(video_ids = "wyrbGSX3jwU", languages="en")

export = YouTubeTranscriptApi.get_transcript(video_id = "wyrbGSX3jwU")

print(export.fetch())

#transcript_list = YouTubeTranscriptApi.list_transcripts(video_id = "wyrbGSX3jwU", languages=['de', 'en'])

# works on command line interface
youtube_transcript_api "wyrbGSX3jwU"

#### EXAMPLE

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts('wyrbGSX3jwU')

print(transcript_list)

# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('de').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
transcript = transcript_list.find_transcript(['de', 'en'])  

# or just filter for manually created transcripts  
transcript = transcript_list.find_manually_created_transcript(['de', 'en'])  

# or automatically generated ones  
transcript = transcript_list.find_generated_transcript(['de', 'en'])


YouTubeTranscriptApi.get_transcript('wyrbGSX3jwU', format=YouTubeTranscriptApi.Format.SRT)
