# Getting Youtube transcripts programmatically https://github.com/jdepoix/youtube-transcript-api
# remote translate of closed captions

#install -> run in the terminal
#pip install youtube_transcript_api
#pip install pandas
from youtube_transcript_api import YouTubeTranscriptApi

# define video id
vidid = "jOKODSnSIQk"

# retrieve the available transcripts
transcript_list = YouTubeTranscriptApi.list_transcripts(vidid)

#print(transcript_list)

# this works own video
export = YouTubeTranscriptApi.get_transcript(video_id = vidid)

print(export)

# determine object type (list)
type(export)

# save list to csv
import pandas as pd

# convert to dataframe
df = pd.DataFrame(export)
# write to csv file
df.to_csv('export.csv', index=False)


# iterate over all available transcripts
for transcript in transcript_list:

    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # whether this transcript can be translated or not
        transcript.is_translatable,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('de').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
transcript = transcript_list.find_transcript(['de', 'en'])  

# or just filter for manually created transcripts  
transcript = transcript_list.find_manually_created_transcript(['de', 'en'])  

# or automatically generated ones  
transcript = transcript_list.find_generated_transcript(['de', 'en'])

# translate
transcript


## Option: translate by youtube api
vidid = "jOKODSnSIQk"

# get all data
transcript_list = YouTubeTranscriptApi.list_transcripts(vidid)

# manually created transcript
transcript = transcript_list.find_manually_created_transcript('en')


## workflow summary that can be used:

# 1. Correct closed captions with Youtube Studio
# 2. Extract as vtt file
# 3. Translate with translateVTT
# 4. Upload back to Youtube


